### DISCUSSION TITLE
how to parse yaml file with custom tag (eg. !!opencv-matrix)?

### DISCUSSION THREAD

**Discussion by realysy** [fktn-k/fkYAML#381] [General]
OpenCV has a capacity to load and dump yaml file: [FileStorage](https://docs.opencv.org/4.10.0/da/d56/classcv_1_1FileStorage.html).

It can dump `cv::Mat` matrix to yaml data like this (note that there is a custom tag `!!opencv-matrix`):
```yaml
%YAML:1.0
---
CameraMat: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.12394459303468e+02, 0., 8.0574744039718894e+02, 0.,
       4.56783221344e+02, 6.33456693933693e+02, 0., 0., 1. ]
DistCoeff: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -5.9912397929941e-01, -9.123454745644473e-01,
       -2.432560172831e-03, 2.87567865372509e-02,
       -9.991769669573e-02 ]
ImageSize: [ 1280, 720 ]
```

and load matrix from yaml file like this:
```cpp
#include <iostream>
#include <string>

#include <opencv2/opencv.hpp>

int cvReadYaml(const std::string& filename) 
{
    // load yaml file
    cv::FileStorage fs(filename, cv::FileStorage::READ);
    if (!fs.isOpened()) {
        std::cerr << "Failed to open file for reading!\n";
        return 1;
    }

    // load matrix
    cv::Mat cam_mat;
    fs["CameraMat"] >> cam_mat;
    std::cout << "CameraMat:\n" << cam_mat << std::endl;

    fs.release();
    return 0;
}
```

I wonder how to do that using fkYAML? to dump and load a custom data struct.
