### DISCUSSION TITLE
I found a parsing bug

### DISCUSSION THREAD

**Discussion by shiyue-code** [fktn-k/fkYAML#484] [Q&A] [answered]
The content of yaml is：
```yaml
test:
    - coords:
      -
      -
      name: "a"
```
Parsing results of yaml-cpp:
```yaml
test:
  - coords:
      - ~
      - ~
    name: a
```

fkyaml result is wrong:
```yaml
test:
  -
    coords:
      - null
      -
        name: a
```

**Comment by fktn-k** [comment]
@shiyue-code   
You're right. The current parser seems to improperly handle indentation at the 5th line.  Can you open an issue for this?

**Reply by fktn-k** [reply, marked as answer]
@shiyue-code   
It's turned out that parsing a block mapping entry `name: "a"` after an empty block sequence entry `- ` is causing the unexpected result, which is not being covered by the parser implementation.  
So, I've created an issue (#488) and a PR for it. Should be fixed soon.

**Reply by fktn-k** [reply]
@shiyue-code   
The PR has been merged which should resolve this issue.  
Could you confirm with the develop HEAD?

**Reply by shiyue-code** [reply]
Sorry for the long delay in replying. I just tried it, and it's working fine now.
```
fkyaml:
test:
  -
    coords:
      - null
      - null
    name: a
````

There’s one more thing I’d like to ask about. Currently, it seems impossible to serialize a string without quotes. Will there be an interface in the future to mark a string for plain text serialization, just like the KEY_PLAIN flag provided by [rapidyaml](https://github.com/biojppm/rapidyaml)？
