### ISSUE TITLE
Misc Parse Errors

### ISSUE THREAD

**Issue by bobziuchkovski** [fktn-k/fkYAML#211]
### Description

While evaluating fkYAML for a project, I ran into several different parse errors on relatively simple YAML structures.

### Reproduction steps

Run a simple parse on the following yaml examples:

`1_single_quote.yml`:
```yaml
stuff:
  - id: 'foo'
    name: Foo
    tags:
      - baz
    params:
      key: 1
  - id: 'bar'
    name: Bar
```

Error: libc++abi: terminating due to uncaught exception of type fkyaml::v0_2_0::exception: multi-line string tokens are unsupported.

Caused by single quoted string values.

`2_single_item_in_sequence.yml`
```yaml
stuff:
  - id: "foo"
    name: Foo
    tags:
      - baz
    params:
      key: 1
  - id: "bar"
    name: Bar
```

Error: libc++abi: terminating due to uncaught exception of type fkyaml::v0_2_0::exception: The node value is not a sequence.

Caused by single item ("baz") in tags sequence. It looks like the parsing expects sequences to always have multiple elements.

`3_reordered.yml`
```yaml
stuff:
  - id: "foo"
    name: Foo
    params:
      key: 1
    tags:
      - baz
  - id: "bar"
    name: Bar
```

No error but the parsed elements are wrong -- the "bar" item is parsed as another item in the tags sequence preceding it. Relates to the same issue shown in #2 above. Parsed structure:

```
stuff:
  -
    id: foo
    name: Foo
    params:
      key: 1
    tags:
      -
        baz: bar
        name: Bar
      - id
```

### Expected vs. actual results

I expected each of these to parse correctly, but they all failed in different ways.

### Compiler and operating system

clang on Mac 13.6

### Library version

develop HEAD

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).
