### ISSUE TITLE
Bug in parsing a block mapping entry right after an empty block sequence entry

### ISSUE THREAD

**Issue by fktn-k** [fktn-k/fkYAML#487]
### Discussed in https://github.com/fktn-k/fkYAML/discussions/484

<div type='discussions-op-text'>

<sup>Originally posted by **shiyue-code** February 14, 2025</sup>
The content of yaml is：
```yaml
test:
    - coords:
      -
      -
      name: "a"
```
Parsing results of yaml-cpp:
```yaml
test:
  - coords:
      - ~
      - ~
    name: a
```

fkyaml result is wrong:
```yaml
test:
  -
    coords:
      - null
      -
        name: a
```

</div>
